import esbuild from 'esbuild'
import process from 'process'
import path from 'path'
import { builtinModules, createRequire } from 'node:module'

const require = createRequire(import.meta.url)

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'
const builtins = [...builtinModules, ...builtinModules.map(name => `node:${name}`)]

/**
 * Resolve @jshph/digest from source (.ts) rather than requiring a pre-built
 * dist/. This way GitHub installs (no dist/) and local file: links both work.
 * esbuild handles the TSâ†’JS compilation during bundling.
 */
function resolveDigestPlugin() {
	return {
		name: 'resolve-digest',
		setup(build) {
			build.onResolve({ filter: /^@jshph\/digest$/ }, args => {
				return { path: require.resolve('@jshph/digest/src/index.ts') }
			})
			// Also resolve sub-path imports like @jshph/digest/core/types
			build.onResolve({ filter: /^@jshph\/digest\// }, args => {
				const sub = args.path.replace('@jshph/digest/', '')
				return { path: require.resolve(`@jshph/digest/src/${sub}`) }
			})
		}
	}
}

function resolveRealtimeBrowserShim() {
	return {
		name: 'resolve-realtime-browser-shim',
		setup(build) {
			build.onResolve({ filter: /^@openai\/agents-realtime\/_shims$/ }, () => {
				const pkg = require.resolve('@openai/agents-realtime/package.json')
				return { path: path.join(path.dirname(pkg), 'dist', 'shims', 'shims-browser.js') }
			})
		}
	}
}

const context = await esbuild.context({
	platform: 'node',
	banner: { js: banner },
	entryPoints: [{ in: 'src/obsidian.ts', out: 'main' }],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins
	],
	format: 'cjs',
	target: 'es2020',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: './',
	plugins: [resolveDigestPlugin(), resolveRealtimeBrowserShim()]
})

if (prod) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
}
